# fly.toml app configuration file generated for fables-be on 2024-12-11T13:52:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fables-be'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.21.6'

[env]
  PORT = ':8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
